import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript } from "@mantine/core";
import Provider from "@/components/shell/provider";
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/charts/styles.css';



const rubik = Rubik({
  weight: ['300','400', '500', '700'],
  display: 'swap',
  variable: '--Rubik',
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "MarketFace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{scrollBehavior: 'smooth'}}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon"  />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body className={rubik.className} >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
